### PR TITLE
Add SBOM blob url to attestation

### PR DESCRIPTION
**Pull request by chmeliik**
https://issues.redhat.com/browse/RHTAP-3063

This is required so that the promotion pipeline can download an SBOM
while guaranteeing that it has not been tampered with. The attestation
is signed => we can trust that the SBOM_BLOB uri was generated by a
trusted pipeline. The SBOM_BLOB uri contains the sha256 digest => we
can verify that the content has not been tampered with.

refs:

- https://slsa.dev/spec/v1.0/provenance#schema
- https://github.com/in-toto/attestation/blob/main/spec/v1/resource_descriptor.md

And other fixes, see individual commit messages.

### CODE REVIEW

**Comment by chmeliik** [comment]
@simonbaird @jduimovich PTAL

**Comment by chmeliik** [comment]
Rebased on main

**Comment by chmeliik** [comment]
Fixed more password handling which was added in main in the meantime

**Review by simonbaird — APPROVED** [review]
Lgtm.

**Review by jduimovich — APPROVED** [review]
This is ok, but one comment on  the env.sh ... Yhe new model will remove the need to have an expanded env.sh in your repo due to the tssc-dev-multi-ci not being "self building"
This have moved to use a users fork of devfile-sample-nodejs-dance  and a matching tssc-dev-gitops to test in CI

**Comment by chmeliik** [comment]
> This is ok, but one comment on the env.sh ... Yhe new model will remove the need to have an expanded env.sh in your repo due to the tssc-dev-multi-ci not being "self building" This have moved to use a users fork of devfile-sample-nodejs-dance and a matching tssc-dev-gitops to test in CI

I'm not sure I understand. What "new model"? :sweat_smile:

**Comment by jduimovich** [comment]
> I'm not sure I understand. What "new model"? 😅

The old repo (tssc-jenkins) had the application source code and the gitops in this same repo so that local test can run as if it had cloned a repo in CI etc... That was messy for this repo and as more people work on it, got tricky.

The new model takes that same code from an external source repo (one for node.js and one for gitops) which means that you can test with your own forks and include updates to gitops fpr deployment, intended t be able to CI test push and pull-requests in the various CIs we support. 
The shared model if you noticed was not good as a demo repo as it included commits every time I ran a demo :) 
From the local dev -- the change is a noop since its all hidden under the covers and works as before if you run build-pipeline.sh

**Pull request merged**
