### PR TITLE
Introduce gitops pipeline for GitLab

### PR DESCRIPTION
**Pull request by simonbaird**
I'm not 100% confident about the way I've set up the rules field, and how/when the workflows are going to be triggered, but let's start with this and see if it behaves the way we want it to.

Also includes some additional minor changes. See commits for details.

### CODE REVIEW

**Comment by simonbaird** [comment]
Need to rework this. The two pipelines don't get used in the same repo, so we need to create two different .gitlab-ci files.

**Comment by simonbaird** [comment]
> Need to rework this. The two pipelines don't get used in the same repo, so we need to create two different .gitlab-ci files.

Done. I'll move out of draft.

**Review by jduimovich — COMMENTED** [review]
Do we need the rules every step ?

**Comment by simonbaird** [comment]
> Do we need the rules every step ? I was thinking the only rule would be in the update deployment step since this pipeline runs all steps except that one in both push and merge requests

Yeah, maybe. I'll revise.

**Comment by simonbaird** [comment]
> > Do we need the rules every step ? I was thinking the only rule would be in the update deployment step since this pipeline runs all steps except that one in both push and merge requests
> 
> Yeah, maybe. I'll revise.

Done now.

**Comment by simonbaird** [comment]
@jduimovich @chmeliik FYI I want to merge this before I go on PTO for a week.

An example of the build pipeline: https://gitlab.com/simonbaird/rhtap-ci-tester/-/pipelines/1500852592

I haven't tested the gitops pipeline, but let's merge anyway and fix any problems later.

**Review by jduimovich — APPROVED** [review]

**Pull request merged**
